### ISSUE TITLE
Can you move the fanuc robot with j519

### ISSUE THREAD

**Issue by chenzlcn** [gavanderhoorn/fanuc_j519_utils#1]
I want to move the robot with J519.
your code works good when i execute the start command
when i  send the moving command, fanuc raised an error.
the error is  
MOTN-601 ST:Sequence No error

I've tried to change the sending way before,but it raised another fault, like
MOTN-610 ST:Execcded Jnt Acc/Dec Limit(A:5,Sq0), etc.
....

Can you give me some help please?

**Comment by gavanderhoorn** [comment]
The scripts in this repository are not intended to be a complete solution to use J519. They only provide some convenience when working with and/or debugging J519.

Your errors seem to indicate you're not sending the controller the information it expects at the times it expects it.

For the Jnt Acc/Dec limit error specifically: you'll need to make sure your position setpoints are smooth, and part of a jerk-limited trajectory.

I would recommend you don't use Python for this, or at least not when doing just-in-time (ie: real-time) closed-loop control. It will not be able to fulfil the timing requirements of J519. If you're sending a trajectory open-loop, you could send more trajectory points to fill the controller's queue. That would reduce the timing requirements on the Python side.

For my own software, I use C++ with a PREEMPT_RT kernel.

**Comment by gavanderhoorn** [comment]
As this is not really an issue with the software in this repository, I'm going to close the issue.

Feel free to keep commenting on it of course.

**Comment by chenzlcn** [comment]
> The scripts in this repository are not intended to be a complete solution to use J519. They only provide some convenience when working with and/or debugging J519.
> 
> Your errors seem to indicate you're not sending the controller the information it expects at the times it expects it.
> 
> For the Jnt Acc/Dec limit error specifically: you'll need to make sure your position setpoints are smooth, and part of a jerk-limited trajectory.
> 
> I would recommend you don't use Python for this, or at least not when doing just-in-time (ie: real-time) closed-loop control. It will not be able to fulfil the timing requirements of J519. If you're sending a trajectory open-loop, you could send more trajectory points to fill the controller's queue. That would reduce the timing requirements on the Python side.
> 
> For my own software, I use C++ with a PREEMPT_RT kernel.

Thanks very much.

**Comment by chibai** [comment]
> s very much.

Dude, I got the same problem~~How did you finish this?
